security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: expenses
            logout:
                    path:   /logout
                    target: /login
                    
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
#-------------------------Inventa Despesas Bundle----------------------------
        - { path: ^/expenses/edit/, role: ROLE_ADMIN }
        - { path: ^/expenses/, role: ROLE_USER }
        - { path: ^/suppliers/edit/, role: ROLE_ADMIN }
        - { path: ^/suppliers/, role: ROLE_USER }
        - { path: ^/currencies/edit/, role: ROLE_ADMIN }
        - { path: ^/currencies/, role: ROLE_USER }
        - { path: ^/transactions/edit/, role: ROLE_ADMIN }
        - { path: ^/transactions/, role: ROLE_USER }
        - { path: ^/categories/, role: ROLE_ADMIN }
        - { path: ^/fos_admin_users/, role: ROLE_SUPER_ADMIN }

