parameters:
#    inventa_example_form.example.class: Inventa\ExampleFormBundle\Example

services:
#    inventa_example_form.example:
#        class: %inventa_example_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
